### ISSUE TITLE
Issue with running action

### ISSUE THREAD

**Issue by kslifter** [carseven/daily-email-notion#1]
My apologies if this is not the proper way to ask a question, but I didn't see a way to message you. My email is ian.hartsook@gmail.com if that is a better way to communicate.

I am working putting this together so I can have the daily email from my notion.

I erased the query so there would be less of a chance for a syntax error. 

I ran the action I got this error. Could you help point me in the right direction for solving the problem? 

Run python dailyEmail/todays-schedule-email.py
Traceback (most recent call last):
  File "/home/runner/work/Notion/Notion/dailyEmail/todays-schedule-email.py", line 32, in <module>
    database_list = utils.decodeDatabase(database)
  File "/home/runner/work/Notion/Notion/dailyEmail/utils.py", line 10, in decodeDatabase
    row_properties[column] = retrievePropertyValue(
  File "/home/runner/work/Notion/Notion/dailyEmail/utils.py", line 4[8](https://github.com/kslifter/Notion/actions/runs/3101268758/jobs/5022447555#step:6:9), in retrievePropertyValue
    value = row["properties"][property]["select"]["name"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

Thanks

-Ian

**Comment by kslifter** [comment]
I ended up working with it some more and I have the action working now. I am still having issues with the syntax in the utils script, but at least I can now work  in a working file. I'm guessing that the syntax has changed some since this was put together.
